
services:
  app:
    build: .
    container_name: spring_SistemasA3
    ports:
      - "8080:8080"
    env_file:
      - ./.env
      
    working_dir: /app
    entrypoint: ["java", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: SistemasA3_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: